apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: azurecicdcontainer.azurecr.io/votingapp:270
        name: vote
        ports:
        - containerPort: 80
          name: vote
      imagePullSecrets:
      - name: acr-secret